name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

variables:
  - name: componentName
    value: 'ecs_logs'

trigger:
  branches:
    include:
      - trunk
      - feature/*
  paths:
    include:
      - ecs_logs/*

resources:
  - repo: self
    clean: true

pool:
  name: Build
  demands:
    - Agent.OS -equals Linux
    - java

steps:
  - task: SonarQubePrepare@7
    inputs:
      SonarQube: 'SonarQube'
      scannerMode: Other
      extraProperties: |
        sonar.projectKey=$(Build.Repository.Name)_$(componentName)
        sonar.projectName=$(Build.Repository.Name)_$(componentName)
        sonar.project.version=$(Build.BuildNumber)
        sonar.SourcesDirectoryRoot: $(componentName)

  - task: versioner@1
    displayName: 'Version'
    name: tag
    inputs:
      prefix: 'v'

  - script: bash generate-branch-version.sh
    workingDirectory: '$(componentName)/deployment'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')
    displayName: 'Branch Version'

  - task: Gradle@3
    displayName: 'Gradle Build'
    inputs:
      gradleWrapperFile: '$(componentName)/gradlew'
      workingDirectory: '$(componentName)'
      tasks: 'clean build jacocoMergedReport generatePomFileForMavenJavaPublication -Pversion=$(tag.version)'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      sonarQubeRunAnalysis: true
      sqGradlePluginVersionChoice: 'build'
    env:
      JAVA_HOME: $(JAVA_HOME_17_X64)

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: '**/TEST-*.xml'

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish Code Coverage'
    inputs:
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/$(componentName)/build/reports/jacocoMergedReport/jacocoMergedReport.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/$(componentName)/build/reports/jacocoMergedReport/html'

  - task: sonar-buildbreaker@8
    displayName: 'Break Build on Quality Gate Failure'
    inputs:
      SonarQube: 'SonarQube'

  - task: CopyFiles@2
    displayName: 'Copy Model Artifact'
    inputs:
      SourceFolder: '$(componentName)/ecs-model/build/'
      Contents: |
        libs/*.jar
        publications/mavenJava/*.xml
      TargetFolder: '$(Build.ArtifactStagingDirectory)/$(componentName)/ecs-model'

  - task: CopyFiles@2
    displayName: 'Copy Core Artifact'
    inputs:
      SourceFolder: '$(componentName)/ecs-core/build/'
      Contents: |
        libs/*.jar
        publications/mavenJava/*.xml
      TargetFolder: '$(Build.ArtifactStagingDirectory)/$(componentName)/ecs-core'

  - task: CopyFiles@2
    displayName: 'Copy Reactive Artifact'
    inputs:
      SourceFolder: '$(componentName)/ecs-reactive/build/'
      Contents: |
        libs/*.jar
        publications/mavenJava/*.xml
      TargetFolder: '$(Build.ArtifactStagingDirectory)/$(componentName)/ecs-reactive'

  - task: CopyFiles@2
    displayName: 'Copy Imperative Artifact'
    inputs:
      SourceFolder: '$(componentName)/ecs-imperative/build/'
      Contents: |
        libs/*.jar
        publications/mavenJava/*.xml
      TargetFolder: '$(Build.ArtifactStagingDirectory)/$(componentName)/ecs-imperative'

  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/trunk'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')))
    displayName: 'Publish to Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: Artifact
